#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 81f4ec5c-e048-4b4a-90a7-1916713b1a4c
# Source File: Admin-Abwesenheitsassistent.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
AwIAAB+LCAAAAAAABACFkV1LwzAUhu8H+w+h91kbrW6DLjAZk134wTq8lTQ9tdE0KUm6sX9vtOnY
UPHuPOSc5+WcZFvgeg/muGKO0fEIoezZ6Hfg7hs8voCxQit6NUmyeIDwthYSNis6I1UK/IZjSNIZ
TouU4XnCppjMye2UXBeEpTyLQ3MYDSm7YwvUi89xkGtZ+jgUn6fZAAHRXSdkuYiSiOaOGde1k9ba
PuuvTpTXzIAvd6aDCG2hAgOKw7pT3PnlFtFG7fUH4HupCyZfW0si2tfW28k/9l98ea0P+IEJtdam
8b4qogN5YXUh7KFf83SWnp6MeBOKya+GR9YAXZaNUHhZHMCCqkE4y6wV1oFy3tv62Sz+MTQeZfHF
p38CIM7zTQMCAAA=#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2017 v5.4.138
     Generated on:       27.06.2022 08:36
     Generated by:       Frank
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2017
#>



#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
2gMAAB+LCAAAAAAABAC9k0tLAzEQgO+C/yH0vGR33a5rIbsglV4EFVfUazadLcE8yiRpyb+3rVJF
QaGHMJd5MPMxL/YIwm4A4w33nOwUJ61pJxe0nHTnZ4Swe5QrabhaSAV3XEPXe44+rOnaOZb/ih5y
rp0DPSgJ7mB/eWKnnbCo5JCR50/WlBZ7ycg8KB8QWgPBI1cZeQi7GuIW4pN9A9MOTcNrUV+Ws2oK
xdWM5ceqPyl9dB50CgZ9kWZpt44uLGqXhLjfVBoQ8q00q1NYRTXWYzOW5bIueMX/Z71qlaSnuUVI
MzyJILzF2ANupICTbuPvMR7Nj0dj+fdf7t4BtbYVHtoDAAA=#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Show-MainForm_psf) -eq 'OK')
	{
		
	}
	
	$script:ExitCode = 0 #Set the exit code for the Packager
}







#endregion Source: Startup.pss

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	
	#Sample function that provides the location of the script
	function Get-ScriptDirectory
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($null -ne $hostinvocation)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	#Sample variable that provides the location of the script
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	#Load Exchange Shell
	try
	{
		Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn
	}
	catch
	{
		Write-Host "Failed to Load Exchange Shell"
		break
	}
	
	#Internal OOF Message
	$InternalMessage = "Hallo Kollegen,

ich bin bis zum XX.XX.XXXX nicht im Haus und bearbeite Mails daher nicht.
Ihre Mail wird nicht automatisch weitergeleitet. Bitte wenden Sie sich in dringenden Fällen an:

Vertretung XX

Mit frerundlichen Grüßen,

Vorname Nachname"
	
	#External OOF Message
	$ExternalMessage = "Sehr geehrte Damen und Herren,

ich bin bis zum XX.XX.XXXX nicht im Haus und bearbeite Mails daher nicht.
Ihre Mail wird nicht automatisch weitergeleitet. Bitte wenden Sie sich in dringenden Fällen an:

Vertretung XX

Mit frerundlichen Grüßen,

Vorname Nachname"
#endregion Source: Globals.ps1

#region Source: MainForm.psf
function Show-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
iWIAAB+LCAAAAAAABADtXV1v4jgUfV9p/0MU7SMLOCF8jCgSpa1UTTsdDd3pal8qA26bbXCQ7Qxl
fv3aSfgoULguId6OopGqKSS55957HE5yw2n7GxmGPwibnWGBLfkf7of0xHbKyO78/ptltW+Y/+hT
HFz4AfmCx6RzjX16EbJxecIf2pWNt5OdBv+SobDEbEJO7P6MCzIu3/l0FE55We2b/CxZ294qWd9T
FLVyVf0rWb0oEBEjJ5REguGgZH2NBoE//Exmt+EzoSeDRgN7Q6+OWm6NVJst26ISyon9II/XHY19
2h1MCSf0ifiCY85ta/jkByMmd7V7IRUsDHiSrsT+lYUTwsQsPUY3EmF/iANy5o8JVbjkpvWShdx2
Zb7pvl2vwxGxOxcy0t59eoFPqOj7P+UOXr1Rsuq1/YFU4e3OW9nu3f2WvAi7E+/659q+vuzPNtT7
G3zl0+crPCDB0bscyEiBinQ3nV4wTJ9n/I4MZMV3dHmzCFfhEAuJx+7UXFeWHaGNrN8q/FsAAAdI
Go2QU7KczT5vaRUeXNIRebE7DgSf3LwvwonduWURBE7ChOl0Wl7mUd6eyPkPSYx57WQBJHGHz2T0
djXuV7ZqV+Ld52yqJHTSIFc+xFJRTgmNxE/C9NgUL/24t8DKL+nn1EqWC+FCSr5VkGDGec7WM9hO
wlXBBJrD+bR54vg/t7obcU7YEw4GY+JTwm7YI8617TWnrtf3bYjhZx2vqU0C1AKTYInNSsBZCh31
eZzwB6PGJaVJLteLOtNcqeHUIZVfocY2xBrUqOpTowmmxgLbL8CMm5uLvsAi2ikqM6WDW5Py02vo
0WEBE8yBuqdPAQiohAISj5UAyqLf3/zhkzruafhy9K4zGUvIWIPwhcsENGXmKR4+98IgZHYn3RhQ
MnXlEG/PwwDLXJplx5tsqvK9pGnASbOeJWDHbwSPbmgwA1M6Pde0WjIjoJqdEw3yOZkQbfHu4Sw7
jYQI6dEJNojDnBIic9X8kFn2G8UniZYHbvirqODmqd45oFW/7B0E01xHQtH8xcl3n0c46ItZQFYW
2VtUXL18iS9K1ipwH7946HVKrozpT4hctIRpcuac4kGgLtwucMD1hYk+xxY4j8qyGphlOniy49ki
ajZMM/QJKH/KFHCQK+VqW26JAT7H5lg1LpKRlEAO6JJnSTyQZIqJ98d5iuiacI4fNwvxMWjg07w5
4MrTQRN+qbwOVIMAzjsI4MAJcEmzJkAvHA/CPLo/VIHkqhLqtvjoyL1X4LGQDXxc7ArUmJeyBitI
5AbqldcV7Asmj1yyxnwYssAfZFGlTrX6qVptV1Q0M9Fdg9GR0dyR0dwdo7k7RnN3jebuGs29ZjT3
mtHcPaO5e0ZzrxvNvW4094bR3BtGc28azb1pNPeW0dxbJnNHRnUdMqrrkFFdh4zqOmRU1yGjug4Z
1XXIqK5DRnUdMqrrkFFdh4zqOmRU1yGjug4Z1XXIqK5DRnUdMqrrkFFdh4zqOseornOM6jrHqK5z
jOo6x6iuc4zqOseornO26Dq9Z1rq6rFp0IPQySDo9cwC/oSKmgNCn7eeT4HgT8umXfiYox8uMBPF
9KeY/hTTn2L6U0x/jEUvpj/F9Cfv6MX0p5j+FNOffKMX059i+pN39GL6U0x/iulPvtGL6U8x/ck7
ejH9KaY/xfQn3+jF9Oeg6Q/S+PbhxtjiqAMguFFGOiv4SKYH5zJHzanPAYYHTU9vzLeECO6wq2+F
Are7iKF8MFuLU/LoU5pvj3UW8ypIcJdr233bdnUZ7miRgsmiz2dYkFt5lvqqzLLY0Rs+kuHUSXES
hzv+t/lWXArcht7S3oAK7r1TlRWCeVgtmr/5FdMP1ss8pvNr3dRZxFvAHrWfm8je8ZTFExk+5/KU
hQok5cqXiF3SM59wMv6H+PIQ0bifW0s91dG6hsbaARr+YayshxyQgcOitXC7BwnN8qk1isFZc3QW
j20/Ns/em4c5zANCFYiMek+YPqqW7CrY/euND7aIwCM/zMmRhKlYidGFEgVjSScuU+1SMQ2ZrmfS
gXYRyIWQI7UK2I0bTuFWU5vCcOOIVWjWHBu1+vm45awxeE/Jfg0Sf1Y+davp0a6mzU5aBrA0PpT0
VQ2PlN15HpX0ILOMd7nYxqlYeDUXuVbSpcJNL5Vthc54qeRqPnWFDzArc1xUsmpwc7qVkGByNjxt
i2XQDZ+Ya1Ao2dlHxRGzsY7Kyy8otWGKuLK8Gb/bnjs2HYPo/oQra1Hh9/yaTe3riz138V7/0uVS
68nCET7fNn1l1snwRmu7sjjqepSk3XnEyJxS+yOqP2eQTyCGp/Hdcf1YVffBe2g8IDTyqtjF+2P9
PQ5yyakXMpJ9oMWvCeXbldU/PdH5D0T47maJYgAA#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formAdminAbwesenheitsass = New-Object 'System.Windows.Forms.Form'
	$linklabelWwwFrankysWebde = New-Object 'System.Windows.Forms.LinkLabel'
	$labelBenutzer = New-Object 'System.Windows.Forms.Label'
	$labelAusserhalbmeinerOrga = New-Object 'System.Windows.Forms.Label'
	$labelInnerhalbMeinerOrgan = New-Object 'System.Windows.Forms.Label'
	$labelOOFStatus = New-Object 'System.Windows.Forms.Label'
	$richtextboxstate = New-Object 'System.Windows.Forms.RichTextBox'
	$buttonBeenden = New-Object 'System.Windows.Forms.Button'
	$buttonSpeichern = New-Object 'System.Windows.Forms.Button'
	$richtextboxexternal = New-Object 'System.Windows.Forms.RichTextBox'
	$richtextinternal = New-Object 'System.Windows.Forms.RichTextBox'
	$comboboxtimend = New-Object 'System.Windows.Forms.ComboBox'
	$comboboxtimestart = New-Object 'System.Windows.Forms.ComboBox'
	$labelEndet = New-Object 'System.Windows.Forms.Label'
	$labelBeginnt = New-Object 'System.Windows.Forms.Label'
	$datetimepickerend = New-Object 'System.Windows.Forms.DateTimePicker'
	$datetimepickerstart = New-Object 'System.Windows.Forms.DateTimePicker'
	$checkboxNurInDiesemZeitraumS = New-Object 'System.Windows.Forms.CheckBox'
	$radiobuttonAutomatischeAntworte = New-Object 'System.Windows.Forms.RadioButton'
	$radiobuttonKeineAutomatischenAn = New-Object 'System.Windows.Forms.RadioButton'
	$buttonLaden = New-Object 'System.Windows.Forms.Button'
	$textboxusername = New-Object 'System.Windows.Forms.TextBox'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	#region Control Helper Functions
	function Update-ComboBox
	{
	<#
		.SYNOPSIS
			This functions helps you load items into a ComboBox.
		
		.DESCRIPTION
			Use this function to dynamically load items into the ComboBox control.
		
		.PARAMETER ComboBox
			The ComboBox control you want to add items to.
		
		.PARAMETER Items
			The object or objects you wish to load into the ComboBox's Items collection.
		
		.PARAMETER DisplayMember
			Indicates the property to display for the items in this control.
		
		.PARAMETER Append
			Adds the item(s) to the ComboBox without clearing the Items collection.
		
		.EXAMPLE
			Update-ComboBox $combobox1 "Red", "White", "Blue"
		
		.EXAMPLE
			Update-ComboBox $combobox1 "Red" -Append
			Update-ComboBox $combobox1 "White" -Append
			Update-ComboBox $combobox1 "Blue" -Append
		
		.EXAMPLE
			Update-ComboBox $combobox1 (Get-Process) "ProcessName"
		
		.NOTES
			Additional information about the function.
	#>
		
		param
		(
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			[System.Windows.Forms.ComboBox]
			$ComboBox,
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			$Items,
			[Parameter(Mandatory = $false)]
			[string]
			$DisplayMember,
			[switch]
			$Append
		)
		
		if (-not $Append)
		{
			$ComboBox.Items.Clear()
		}
		
		if ($Items -is [Object[]])
		{
			$ComboBox.Items.AddRange($Items)
		}
		elseif ($Items -is [System.Collections.IEnumerable])
		{
			$ComboBox.BeginUpdate()
			foreach ($obj in $Items)
			{
				$ComboBox.Items.Add($obj)
			}
			$ComboBox.EndUpdate()
		}
		else
		{
			$ComboBox.Items.Add($Items)
		}
		
		$ComboBox.DisplayMember = $DisplayMember
	}
	
	function Update-ListBox
	{
	<#
		.SYNOPSIS
			This functions helps you load items into a ListBox or CheckedListBox.
		
		.DESCRIPTION
			Use this function to dynamically load items into the ListBox control.
		
		.PARAMETER ListBox
			The ListBox control you want to add items to.
		
		.PARAMETER Items
			The object or objects you wish to load into the ListBox's Items collection.
		
		.PARAMETER DisplayMember
			Indicates the property to display for the items in this control.
		
		.PARAMETER Append
			Adds the item(s) to the ListBox without clearing the Items collection.
		
		.EXAMPLE
			Update-ListBox $ListBox1 "Red", "White", "Blue"
		
		.EXAMPLE
			Update-ListBox $listBox1 "Red" -Append
			Update-ListBox $listBox1 "White" -Append
			Update-ListBox $listBox1 "Blue" -Append
		
		.EXAMPLE
			Update-ListBox $listBox1 (Get-Process) "ProcessName"
		
		.NOTES
			Additional information about the function.
	#>
		
		param
		(
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			[System.Windows.Forms.ListBox]
			$ListBox,
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			$Items,
			[Parameter(Mandatory = $false)]
			[string]
			$DisplayMember,
			[switch]
			$Append
		)
		
		if (-not $Append)
		{
			$listBox.Items.Clear()
		}
		
		if ($Items -is [System.Windows.Forms.ListBox+ObjectCollection])
		{
			$listBox.Items.AddRange($Items)
		}
		elseif ($Items -is [Array])
		{
			$listBox.BeginUpdate()
			foreach ($obj in $Items)
			{
				$listBox.Items.Add($obj)
			}
			$listBox.EndUpdate()
		}
		else
		{
			$listBox.Items.Add($Items)
		}
		
		$listBox.DisplayMember = $DisplayMember
	}
	#endregion
	$global:Loadsuccess = $false
	
	$buttonLaden_Click = {
		#load user
		try
		{
			$username = $textboxusername.Text
			$global:mailbox = get-mailbox $username -ea stop
			if ($global:mailbox)
			{			
				#current OOF state
				Write-Host "Successfully loaded Mailbox"
				$state = Get-MailboxAutoReplyConfiguration $global:mailbox | select AutoReplyState, starttime, endtime
				$status = $state.AutoReplyState
				$start = $state.starttime
				$end = $state.endtime
				$statetext = "
Status:    $status
Startzeit: $start
Endzeit:   $end
"
				$richtextboxstate.Text = $statetext
				$global:Loadsuccess = $true
			}
	
		}
		catch
		{
			Write-Host "Loading Mailbox Failed"
			#Display message box if user load failed
			[System.Windows.Forms.MessageBox]::Show("Benutzer nicht gefunden: $username", 'Fehler', 'OK', 'Error')
			
			#Disable all controls if user load failed
			$global:Loadsuccess = $false
			$statetext = ""
			$richtextboxstate.Text = $statetext
			$radiobuttonKeineAutomatischenAn.Enabled = $false
			$radiobuttonAutomatischeAntworte.Enabled = $false
			$checkboxNurInDiesemZeitraumS.Enabled = $false
			$buttonSpeichern.Enabled = $false
			$datetimepickerstart.Enabled = $false
			$comboboxtimestart.Enabled = $false
			$datetimepickerend.Enabled = $false
			$comboboxtimend.Enabled = $false
			$richtextinternal.Enabled = $false
			$richtextboxexternal.Enabled = $false
		}
		
		#Enable Controls if User loaded successfully
		if ($global:Loadsuccess -eq $true)
		{
			$radiobuttonKeineAutomatischenAn.Enabled = $true
			$radiobuttonAutomatischeAntworte.Enabled = $true
			$checkboxNurInDiesemZeitraumS.Enabled = $true
			$buttonSpeichern.Enabled = $true
		}
	}
	
	$buttonBeenden_Click = {
		#Close this tool
		$formAdminAbwesenheitsass.close()
	}
	
	$buttonSpeichern_Click={
		#Save OOF
		Write-Host $Loadsuccess
		if ($LoadSuccess -eq $true)
		{
			#Disable OOF
			if ($radiobuttonKeineAutomatischenAn.Checked -eq $true)
			{
				Write-Host "Disbale OOF for $global:mailbox"
				try
				{
					Set-MailboxAutoReplyConfiguration -Identity $global:mailbox -AutoReplyState disabled
					Write-Host "OOF disabled" 
				}
				catch
				{
					Write-Host "Disbale OOF failed"
				}
			}
			#Enable OOF without timeframe
			if ($radiobuttonAutomatischeAntworte.Checked -eq $true -and $checkboxNurInDiesemZeitraumS.Checked -eq $false)
			{
				try
				{
					Write-Host "Enable without TimeFrame"
					$InternalMessage = $richtextinternal.Text
					$ExternalMessage = $richtextboxexternal.Text
					Set-MailboxAutoReplyConfiguration -Identity $global:mailbox -AutoReplyState enabled -InternalMessage $InternalMessage -ExternalMessage $ExternalMessage
				}
				catch
				{
					Write-Host "OOF with Timeframe failed"
				}
			}
			
			#Enable OOF with timeframe
			if ($radiobuttonAutomatischeAntworte.Checked -eq $true -and $checkboxNurInDiesemZeitraumS.Checked -eq $true)
			{
				Write-Host "Enable with TimeFrame"
				$InternalMessage = $richtextinternal.Text
				$ExternalMessage = $richtextboxexternal.Text
				$hourstart = $comboboxtimestart.Text.Split(":")[0]
				$minutesstart = $comboboxtimestart.Text.Split(":")[1]
				$hourend = $comboboxtimend.Text.Split(":")[0]
				$minutesend = $comboboxtimend.Text.Split(":")[1]
				[datetime]$start = Get-Date $datetimepickerstart.Text -Hour $hourstart -Minute $minutesstart
				[datetime]$end = Get-Date $datetimepickerend.Text -Hour $hourend -Minute $minutesend
				Write-Host "$start"
				Write-Host "$end"
				Set-MailboxAutoReplyConfiguration -Identity $global:mailbox -AutoReplyState scheduled -InternalMessage $InternalMessage -ExternalMessage $ExternalMessage -StartTime $start -EndTime $end
			}
		}
	}
	
	$checkboxNurInDiesemZeitraumS_CheckedChanged={
		#enable controls if needed
		if ($checkboxNurInDiesemZeitraumS.Checked -eq $true)
		{
			$datetimepickerstart.Enabled = $true
			$comboboxtimestart.Enabled = $true
			$datetimepickerend.Enabled = $true
			$comboboxtimend.Enabled = $true
		}
		if ($checkboxNurInDiesemZeitraumS.Checked -eq $false)
		{
			$datetimepickerstart.Enabled = $false
			$comboboxtimestart.Enabled = $false
			$datetimepickerend.Enabled = $false
			$comboboxtimend.Enabled = $false
		}
		
	}
	
	$radiobuttonAutomatischeAntworte_CheckedChanged={
		#Enable controls if needed
		if ($radiobuttonAutomatischeAntworte.Checked -eq $true)
		{
			$richtextinternal.Enabled = $true
			$richtextboxexternal.Enabled = $true
		}
		else
		{
			$richtextinternal.Enabled = $false
			$richtextboxexternal.Enabled = $false
		}
	}
	
	$radiobuttonKeineAutomatischenAn_CheckedChanged={
		#Disable controls if not needed
		if ($radiobuttonKeineAutomatischenAn.Checked -eq $true)
		{
			$richtextinternal.Enabled = $false
			$richtextboxexternal.Enabled = $false
		}
		else
		{
			$richtextinternal.Enabled = $true
			$richtextboxexternal.Enabled = $true
		}
	}
	
	$linklabelWwwFrankysWebde_LinkClicked=[System.Windows.Forms.LinkLabelLinkClickedEventHandler]{
	#Event Argument: $_ = [System.Windows.Forms.LinkLabelLinkClickedEventArgs]
		Start-Process "https://www.frankysweb.de"
		
	}
		# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formAdminAbwesenheitsass.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_richtextboxstate = $richtextboxstate.Text
		$script:MainForm_richtextboxexternal = $richtextboxexternal.Text
		$script:MainForm_richtextinternal = $richtextinternal.Text
		$script:MainForm_comboboxtimend = $comboboxtimend.Text
		$script:MainForm_comboboxtimend_SelectedItem = $comboboxtimend.SelectedItem
		$script:MainForm_comboboxtimestart = $comboboxtimestart.Text
		$script:MainForm_comboboxtimestart_SelectedItem = $comboboxtimestart.SelectedItem
		$script:MainForm_datetimepickerend = $datetimepickerend.Value
		$script:MainForm_datetimepickerstart = $datetimepickerstart.Value
		$script:MainForm_checkboxNurInDiesemZeitraumS = $checkboxNurInDiesemZeitraumS.Checked
		$script:MainForm_radiobuttonAutomatischeAntworte = $radiobuttonAutomatischeAntworte.Checked
		$script:MainForm_radiobuttonKeineAutomatischenAn = $radiobuttonKeineAutomatischenAn.Checked
		$script:MainForm_textboxusername = $textboxusername.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$linklabelWwwFrankysWebde.remove_LinkClicked($linklabelWwwFrankysWebde_LinkClicked)
			$buttonBeenden.remove_Click($buttonBeenden_Click)
			$buttonSpeichern.remove_Click($buttonSpeichern_Click)
			$checkboxNurInDiesemZeitraumS.remove_CheckedChanged($checkboxNurInDiesemZeitraumS_CheckedChanged)
			$radiobuttonAutomatischeAntworte.remove_CheckedChanged($radiobuttonAutomatischeAntworte_CheckedChanged)
			$radiobuttonKeineAutomatischenAn.remove_CheckedChanged($radiobuttonKeineAutomatischenAn_CheckedChanged)
			$buttonLaden.remove_Click($buttonLaden_Click)
			$formAdminAbwesenheitsass.remove_Load($Form_StateCorrection_Load)
			$formAdminAbwesenheitsass.remove_Closing($Form_StoreValues_Closing)
			$formAdminAbwesenheitsass.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formAdminAbwesenheitsass.SuspendLayout()
	#
	# formAdminAbwesenheitsass
	#
	$formAdminAbwesenheitsass.Controls.Add($linklabelWwwFrankysWebde)
	$formAdminAbwesenheitsass.Controls.Add($labelBenutzer)
	$formAdminAbwesenheitsass.Controls.Add($labelAusserhalbmeinerOrga)
	$formAdminAbwesenheitsass.Controls.Add($labelInnerhalbMeinerOrgan)
	$formAdminAbwesenheitsass.Controls.Add($labelOOFStatus)
	$formAdminAbwesenheitsass.Controls.Add($richtextboxstate)
	$formAdminAbwesenheitsass.Controls.Add($buttonBeenden)
	$formAdminAbwesenheitsass.Controls.Add($buttonSpeichern)
	$formAdminAbwesenheitsass.Controls.Add($richtextboxexternal)
	$formAdminAbwesenheitsass.Controls.Add($richtextinternal)
	$formAdminAbwesenheitsass.Controls.Add($comboboxtimend)
	$formAdminAbwesenheitsass.Controls.Add($comboboxtimestart)
	$formAdminAbwesenheitsass.Controls.Add($labelEndet)
	$formAdminAbwesenheitsass.Controls.Add($labelBeginnt)
	$formAdminAbwesenheitsass.Controls.Add($datetimepickerend)
	$formAdminAbwesenheitsass.Controls.Add($datetimepickerstart)
	$formAdminAbwesenheitsass.Controls.Add($checkboxNurInDiesemZeitraumS)
	$formAdminAbwesenheitsass.Controls.Add($radiobuttonAutomatischeAntworte)
	$formAdminAbwesenheitsass.Controls.Add($radiobuttonKeineAutomatischenAn)
	$formAdminAbwesenheitsass.Controls.Add($buttonLaden)
	$formAdminAbwesenheitsass.Controls.Add($textboxusername)
	$formAdminAbwesenheitsass.AutoScaleDimensions = '6, 13'
	$formAdminAbwesenheitsass.AutoScaleMode = 'Font'
	$formAdminAbwesenheitsass.ClientSize = '567, 643'
	$formAdminAbwesenheitsass.Name = 'formAdminAbwesenheitsass'
	$formAdminAbwesenheitsass.Text = 'Admin-Abwesenheitsassistent'
	#
	# linklabelWwwFrankysWebde
	#
	$linklabelWwwFrankysWebde.Location = '433, 611'
	$linklabelWwwFrankysWebde.Name = 'linklabelWwwFrankysWebde'
	$linklabelWwwFrankysWebde.Size = '112, 23'
	$linklabelWwwFrankysWebde.TabIndex = 21
	$linklabelWwwFrankysWebde.TabStop = $True
	$linklabelWwwFrankysWebde.Text = 'www.FrankysWeb.de'
	$linklabelWwwFrankysWebde.add_LinkClicked($linklabelWwwFrankysWebde_LinkClicked)
	#
	# labelBenutzer
	#
	$labelBenutzer.AutoSize = $True
	$labelBenutzer.Location = '24, 33'
	$labelBenutzer.Name = 'labelBenutzer'
	$labelBenutzer.Size = '52, 13'
	$labelBenutzer.TabIndex = 20
	$labelBenutzer.Text = 'Benutzer:'
	#
	# labelAusserhalbmeinerOrga
	#
	$labelAusserhalbmeinerOrga.AutoSize = $True
	$labelAusserhalbmeinerOrga.Location = '24, 426'
	$labelAusserhalbmeinerOrga.Name = 'labelAusserhalbmeinerOrga'
	$labelAusserhalbmeinerOrga.Size = '158, 13'
	$labelAusserhalbmeinerOrga.TabIndex = 19
	$labelAusserhalbmeinerOrga.Text = 'Ausserhalb meiner Organisation:'
	#
	# labelInnerhalbMeinerOrgan
	#
	$labelInnerhalbMeinerOrgan.AutoSize = $True
	$labelInnerhalbMeinerOrgan.Location = '24, 269'
	$labelInnerhalbMeinerOrgan.Name = 'labelInnerhalbMeinerOrgan'
	$labelInnerhalbMeinerOrgan.Size = '150, 13'
	$labelInnerhalbMeinerOrgan.TabIndex = 18
	$labelInnerhalbMeinerOrgan.Text = 'Innerhalb meiner Organisation:'
	#
	# labelOOFStatus
	#
	$labelOOFStatus.AutoSize = $True
	$labelOOFStatus.Location = '346, 57'
	$labelOOFStatus.Name = 'labelOOFStatus'
	$labelOOFStatus.Size = '65, 13'
	$labelOOFStatus.TabIndex = 17
	$labelOOFStatus.Text = 'OOF Status:'
	#
	# richtextboxstate
	#
	$richtextboxstate.BackColor = 'Control'
	$richtextboxstate.Font = 'Consolas, 8.25pt'
	$richtextboxstate.Location = '346, 77'
	$richtextboxstate.Name = 'richtextboxstate'
	$richtextboxstate.ReadOnly = $True
	$richtextboxstate.Size = '199, 81'
	$richtextboxstate.TabIndex = 16
	$richtextboxstate.Text = ''
	#
	# buttonBeenden
	#
	$buttonBeenden.Location = '146, 595'
	$buttonBeenden.Name = 'buttonBeenden'
	$buttonBeenden.Size = '99, 27'
	$buttonBeenden.TabIndex = 15
	$buttonBeenden.Text = 'Beenden'
	$buttonBeenden.UseVisualStyleBackColor = $True
	$buttonBeenden.add_Click($buttonBeenden_Click)
	#
	# buttonSpeichern
	#
	$buttonSpeichern.Enabled = $False
	$buttonSpeichern.Location = '24, 595'
	$buttonSpeichern.Name = 'buttonSpeichern'
	$buttonSpeichern.Size = '99, 27'
	$buttonSpeichern.TabIndex = 14
	$buttonSpeichern.Text = 'Speichern'
	$buttonSpeichern.UseVisualStyleBackColor = $True
	$buttonSpeichern.add_Click($buttonSpeichern_Click)
	#
	# richtextboxexternal
	#
	$richtextboxexternal.Enabled = $False
	$richtextboxexternal.Location = '24, 443'
	$richtextboxexternal.Name = 'richtextboxexternal'
	$richtextboxexternal.Size = '521, 129'
	$richtextboxexternal.TabIndex = 13
	$richtextboxexternal.Text = "$ExternalMessage"
	#
	# richtextinternal
	#
	$richtextinternal.Enabled = $False
	$richtextinternal.Location = '23, 286'
	$richtextinternal.Name = 'richtextinternal'
	$richtextinternal.Size = '522, 129'
	$richtextinternal.TabIndex = 12
	$richtextinternal.Text = "$InternalMessage"
	#
	# comboboxtimend
	#
	$comboboxtimend.Enabled = $False
	$comboboxtimend.FormattingEnabled = $True
	[void]$comboboxtimend.Items.Add('00:00')
	[void]$comboboxtimend.Items.Add('00:30')
	[void]$comboboxtimend.Items.Add('01:00')
	[void]$comboboxtimend.Items.Add('01:30')
	[void]$comboboxtimend.Items.Add('02:00')
	[void]$comboboxtimend.Items.Add('02:30')
	[void]$comboboxtimend.Items.Add('03:00')
	[void]$comboboxtimend.Items.Add('03:30')
	[void]$comboboxtimend.Items.Add('04:00')
	[void]$comboboxtimend.Items.Add('04:30')
	[void]$comboboxtimend.Items.Add('05:00')
	[void]$comboboxtimend.Items.Add('05:30')
	[void]$comboboxtimend.Items.Add('06:00')
	[void]$comboboxtimend.Items.Add('06:30')
	[void]$comboboxtimend.Items.Add('07:00')
	[void]$comboboxtimend.Items.Add('07:30')
	[void]$comboboxtimend.Items.Add('08:00')
	[void]$comboboxtimend.Items.Add('08:30')
	[void]$comboboxtimend.Items.Add('09:00')
	[void]$comboboxtimend.Items.Add('09:30')
	[void]$comboboxtimend.Items.Add('10:00')
	[void]$comboboxtimend.Items.Add('10:30')
	[void]$comboboxtimend.Items.Add('11:00')
	[void]$comboboxtimend.Items.Add('11:30')
	[void]$comboboxtimend.Items.Add('12:00')
	[void]$comboboxtimend.Items.Add('12:30')
	[void]$comboboxtimend.Items.Add('13:00')
	[void]$comboboxtimend.Items.Add('13:30')
	[void]$comboboxtimend.Items.Add('14:00')
	[void]$comboboxtimend.Items.Add('14:30')
	[void]$comboboxtimend.Items.Add('15:00')
	[void]$comboboxtimend.Items.Add('15:30')
	[void]$comboboxtimend.Items.Add('16:00')
	[void]$comboboxtimend.Items.Add('16:30')
	[void]$comboboxtimend.Items.Add('17:00')
	[void]$comboboxtimend.Items.Add('17:30')
	[void]$comboboxtimend.Items.Add('18:00')
	[void]$comboboxtimend.Items.Add('18:30')
	[void]$comboboxtimend.Items.Add('19:00')
	[void]$comboboxtimend.Items.Add('19:30')
	[void]$comboboxtimend.Items.Add('20:00')
	[void]$comboboxtimend.Items.Add('20:30')
	[void]$comboboxtimend.Items.Add('21:00')
	[void]$comboboxtimend.Items.Add('21:30')
	[void]$comboboxtimend.Items.Add('22:00')
	[void]$comboboxtimend.Items.Add('22:30')
	[void]$comboboxtimend.Items.Add('23:00')
	[void]$comboboxtimend.Items.Add('23:30')
	$comboboxtimend.Location = '362, 221'
	$comboboxtimend.Name = 'comboboxtimend'
	$comboboxtimend.Size = '121, 21'
	$comboboxtimend.TabIndex = 10
	$comboboxtimend.Text = '23:00'
	#
	# comboboxtimestart
	#
	$comboboxtimestart.Enabled = $False
	$comboboxtimestart.FormattingEnabled = $True
	[void]$comboboxtimestart.Items.Add('00:00')
	[void]$comboboxtimestart.Items.Add('00:30')
	[void]$comboboxtimestart.Items.Add('01:00')
	[void]$comboboxtimestart.Items.Add('01:30')
	[void]$comboboxtimestart.Items.Add('02:00')
	[void]$comboboxtimestart.Items.Add('02:30')
	[void]$comboboxtimestart.Items.Add('03:00')
	[void]$comboboxtimestart.Items.Add('03:30')
	[void]$comboboxtimestart.Items.Add('04:00')
	[void]$comboboxtimestart.Items.Add('04:30')
	[void]$comboboxtimestart.Items.Add('05:00')
	[void]$comboboxtimestart.Items.Add('05:30')
	[void]$comboboxtimestart.Items.Add('06:00')
	[void]$comboboxtimestart.Items.Add('06:30')
	[void]$comboboxtimestart.Items.Add('07:00')
	[void]$comboboxtimestart.Items.Add('07:30')
	[void]$comboboxtimestart.Items.Add('08:00')
	[void]$comboboxtimestart.Items.Add('08:30')
	[void]$comboboxtimestart.Items.Add('09:00')
	[void]$comboboxtimestart.Items.Add('09:30')
	[void]$comboboxtimestart.Items.Add('10:00')
	[void]$comboboxtimestart.Items.Add('10:30')
	[void]$comboboxtimestart.Items.Add('11:00')
	[void]$comboboxtimestart.Items.Add('11:30')
	[void]$comboboxtimestart.Items.Add('12:00')
	[void]$comboboxtimestart.Items.Add('12:30')
	[void]$comboboxtimestart.Items.Add('13:00')
	[void]$comboboxtimestart.Items.Add('13:30')
	[void]$comboboxtimestart.Items.Add('14:00')
	[void]$comboboxtimestart.Items.Add('14:30')
	[void]$comboboxtimestart.Items.Add('15:00')
	[void]$comboboxtimestart.Items.Add('15:30')
	[void]$comboboxtimestart.Items.Add('16:00')
	[void]$comboboxtimestart.Items.Add('16:30')
	[void]$comboboxtimestart.Items.Add('17:00')
	[void]$comboboxtimestart.Items.Add('17:30')
	[void]$comboboxtimestart.Items.Add('18:00')
	[void]$comboboxtimestart.Items.Add('18:30')
	[void]$comboboxtimestart.Items.Add('19:00')
	[void]$comboboxtimestart.Items.Add('19:30')
	[void]$comboboxtimestart.Items.Add('20:00')
	[void]$comboboxtimestart.Items.Add('20:30')
	[void]$comboboxtimestart.Items.Add('21:00')
	[void]$comboboxtimestart.Items.Add('21:30')
	[void]$comboboxtimestart.Items.Add('22:00')
	[void]$comboboxtimestart.Items.Add('22:30')
	[void]$comboboxtimestart.Items.Add('23:00')
	[void]$comboboxtimestart.Items.Add('23:30')
	$comboboxtimestart.Location = '362, 195'
	$comboboxtimestart.Name = 'comboboxtimestart'
	$comboboxtimestart.Size = '121, 21'
	$comboboxtimestart.TabIndex = 9
	$comboboxtimestart.Text = '00:00'
	#
	# labelEndet
	#
	$labelEndet.AutoSize = $True
	$labelEndet.Location = '85, 221'
	$labelEndet.Name = 'labelEndet'
	$labelEndet.Size = '38, 13'
	$labelEndet.TabIndex = 8
	$labelEndet.Text = 'Endet:'
	#
	# labelBeginnt
	#
	$labelBeginnt.AutoSize = $True
	$labelBeginnt.Location = '85, 195'
	$labelBeginnt.Name = 'labelBeginnt'
	$labelBeginnt.Size = '46, 13'
	$labelBeginnt.TabIndex = 7
	$labelBeginnt.Text = 'Beginnt:'
	#
	# datetimepickerend
	#
	$datetimepickerend.Enabled = $False
	$datetimepickerend.Location = '137, 221'
	$datetimepickerend.Name = 'datetimepickerend'
	$datetimepickerend.Size = '200, 20'
	$datetimepickerend.TabIndex = 6
	#
	# datetimepickerstart
	#
	$datetimepickerstart.Enabled = $False
	$datetimepickerstart.Location = '137, 195'
	$datetimepickerstart.Name = 'datetimepickerstart'
	$datetimepickerstart.Size = '200, 20'
	$datetimepickerstart.TabIndex = 5
	#
	# checkboxNurInDiesemZeitraumS
	#
	$checkboxNurInDiesemZeitraumS.Enabled = $False
	$checkboxNurInDiesemZeitraumS.Location = '57, 165'
	$checkboxNurInDiesemZeitraumS.Name = 'checkboxNurInDiesemZeitraumS'
	$checkboxNurInDiesemZeitraumS.Size = '365, 24'
	$checkboxNurInDiesemZeitraumS.TabIndex = 4
	$checkboxNurInDiesemZeitraumS.Text = 'Nur in diesem Zeitraum senden:'
	$checkboxNurInDiesemZeitraumS.UseVisualStyleBackColor = $True
	$checkboxNurInDiesemZeitraumS.add_CheckedChanged($checkboxNurInDiesemZeitraumS_CheckedChanged)
	#
	# radiobuttonAutomatischeAntworte
	#
	$radiobuttonAutomatischeAntworte.Enabled = $False
	$radiobuttonAutomatischeAntworte.Location = '24, 134'
	$radiobuttonAutomatischeAntworte.Name = 'radiobuttonAutomatischeAntworte'
	$radiobuttonAutomatischeAntworte.Size = '398, 24'
	$radiobuttonAutomatischeAntworte.TabIndex = 3
	$radiobuttonAutomatischeAntworte.Text = 'Automatische Antworten Senden'
	$radiobuttonAutomatischeAntworte.UseVisualStyleBackColor = $True
	$radiobuttonAutomatischeAntworte.add_CheckedChanged($radiobuttonAutomatischeAntworte_CheckedChanged)
	#
	# radiobuttonKeineAutomatischenAn
	#
	$radiobuttonKeineAutomatischenAn.Checked = $True
	$radiobuttonKeineAutomatischenAn.Enabled = $False
	$radiobuttonKeineAutomatischenAn.Location = '24, 103'
	$radiobuttonKeineAutomatischenAn.Name = 'radiobuttonKeineAutomatischenAn'
	$radiobuttonKeineAutomatischenAn.Size = '398, 24'
	$radiobuttonKeineAutomatischenAn.TabIndex = 2
	$radiobuttonKeineAutomatischenAn.TabStop = $True
	$radiobuttonKeineAutomatischenAn.Text = 'Keine automatischen Anworten senden'
	$radiobuttonKeineAutomatischenAn.UseVisualStyleBackColor = $True
	$radiobuttonKeineAutomatischenAn.add_CheckedChanged($radiobuttonKeineAutomatischenAn_CheckedChanged)
	#
	# buttonLaden
	#
	$buttonLaden.Location = '231, 47'
	$buttonLaden.Name = 'buttonLaden'
	$buttonLaden.Size = '75, 23'
	$buttonLaden.TabIndex = 1
	$buttonLaden.Text = 'Laden'
	$buttonLaden.UseVisualStyleBackColor = $True
	$buttonLaden.add_Click($buttonLaden_Click)
	#
	# textboxusername
	#
	$textboxusername.Location = '24, 50'
	$textboxusername.Name = 'textboxusername'
	$textboxusername.Size = '188, 20'
	$textboxusername.TabIndex = 0
	$formAdminAbwesenheitsass.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formAdminAbwesenheitsass.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formAdminAbwesenheitsass.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formAdminAbwesenheitsass.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$formAdminAbwesenheitsass.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $formAdminAbwesenheitsass.ShowDialog()

}
#endregion Source: MainForm.psf

#Start the application
Main ($CommandLine)
